### ISSUE TITLE
Deployment fails due to deprecated arn policy

### ISSUE THREAD

**Issue by joe4dev** [perfkit/hello-retail#4]
`sb prepare` fails with the following error:

```
An error occurred: RetailStreamReader - Policy arn:aws:iam::aws:policy/AWSLambdaFullAccess does not exist or is not attachable. (Service: AmazonIdentityManagement; Status Code: 404; Error Code: NoSuchEntity; Request ID: REDACTED; Proxy: null).
INFO:run:      at /apps/hello-retail/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:94:23
```

It seems the app uses a deprecated AWS feature that is now removed: https://forum.serverless.com/t/policy-arniam-policy-awslambdafullaccess-does-not-exist-or-is-not-attachable/14537

It also seems that @simontrapp has a fix for that 😄.   👏. 👏. 👏
https://github.com/simontrapp/hello-retail/commit/28f5a1099fddd33dfae02d242e0dc37956b84f9b

**Comment by simontrapp** [comment]
I committed a fix for the problem
